### ISSUE TITLE
How to install correctly

### ISSUE THREAD

**Issue by derjape** [BeFlE/SoMoSe#18]
Hi,

I bought 3 sensors via Amazon to measure the soil moisture of my lawn on different locations.
Is there a recommendation how to "install" it? Is it better to dig it in, in horizontal or vertical orientation? What are pro or cons of the different orientation? 
I miss this information within the documentation.
Thanks!

**Comment by BeFlE** [comment]
Hi,

the SoMoSe should be installed as vertically as possible.
In a horizontal installation position, the sensor sometimes does not provide reliable data.

To install the sensor, simply press it carefully into the ground. If the ground at the installation site is very solid, it is advisable to loosen it. A small opening can also be created, e.g. a spade cut, and the sensor inserted into it.


Best regards
Christian
